### ISSUE TITLE
Could not import your Project ... There is no artisan file 

### ISSUE THREAD

**Issue by elarib** [dbakiu/smk#1]
Hi,
I hope you re doing great ! 
I tried to import the project, but the artisan file does not exit , so i can't artisan and i can't composer update , it gives me always Could not open input file: artisan .... 
Also the app.php file bootstrap/app.php i can't find it ...

**Comment by dbakiu** [comment]
@elarib 
Hey there.

The app.php file in the bootstrap folder doesn't exist in my local environment either. As for the artisan file, that is also empty locally. If you have any idea on how I could help out, let me know.

**Comment by elarib** [comment]
Hi,
thank you for your response :)
But how can i deploy it .?

**Comment by dbakiu** [comment]
@elarib 
I'll try and deploy it on another environment as soon as I can and I'll let you know.

**Comment by Egzonaa** [comment]
Hi,
Could you please help me out with the "emb" column in the donors table. What does emb refers to?

Thank you.

**Comment by dbakiu** [comment]
Hi @Egzonaa,

EMB is the social security number (SSN). In hindsight, it shouldn't even be stored, but that's what it refers to.
